# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from priva_common.dataplane.v1 import account_pb2 as priva__common_dot_dataplane_dot_v1_dot_account__pb2
from priva_common.dataplane.v1 import common_pb2 as priva__common_dot_dataplane_dot_v1_dot_common__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in priva_common/dataplane/v1/account_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/priva.dataplane.v1.AccountService/Get',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.FromString,
                _registered_method=True)
        self.GetByUsername = channel.unary_unary(
                '/priva.dataplane.v1.AccountService/GetByUsername',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.UsernameRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/priva.dataplane.v1.AccountService/List',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.AccountList.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/priva.dataplane.v1.AccountService/Create',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.CreateAccountRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/priva.dataplane.v1.AccountService/Update',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.UpdateAccountRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/priva.dataplane.v1.AccountService/Delete',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.VerifyPassword = channel.unary_unary(
                '/priva.dataplane.v1.AccountService/VerifyPassword',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.VerifyPasswordRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.BoolValue.FromString,
                _registered_method=True)
        self.FindByApiKey = channel.unary_unary(
                '/priva.dataplane.v1.AccountService/FindByApiKey',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.ApiKeyRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.FromString,
                _registered_method=True)
        self.CountAdmins = channel.unary_unary(
                '/priva.dataplane.v1.AccountService/CountAdmins',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.CountValue.FromString,
                _registered_method=True)
        self.FindByFeishuUserId = channel.unary_unary(
                '/priva.dataplane.v1.AccountService/FindByFeishuUserId',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.FeishuRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.FromString,
                _registered_method=True)


class AccountServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetByUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindByApiKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountAdmins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindByFeishuUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.SerializeToString,
            ),
            'GetByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.GetByUsername,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.UsernameRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.AccountList.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.CreateAccountRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.UpdateAccountRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
            ),
            'VerifyPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPassword,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.VerifyPasswordRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.BoolValue.SerializeToString,
            ),
            'FindByApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.FindByApiKey,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.ApiKeyRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.SerializeToString,
            ),
            'CountAdmins': grpc.unary_unary_rpc_method_handler(
                    servicer.CountAdmins,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.CountValue.SerializeToString,
            ),
            'FindByFeishuUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.FindByFeishuUserId,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.FeishuRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'priva.dataplane.v1.AccountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('priva.dataplane.v1.AccountService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.AccountService/Get',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.AccountService/GetByUsername',
            priva__common_dot_dataplane_dot_v1_dot_account__pb2.UsernameRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.AccountService/List',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_account__pb2.AccountList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.AccountService/Create',
            priva__common_dot_dataplane_dot_v1_dot_account__pb2.CreateAccountRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.AccountService/Update',
            priva__common_dot_dataplane_dot_v1_dot_account__pb2.UpdateAccountRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.AccountService/Delete',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.AccountService/VerifyPassword',
            priva__common_dot_dataplane_dot_v1_dot_account__pb2.VerifyPasswordRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindByApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.AccountService/FindByApiKey',
            priva__common_dot_dataplane_dot_v1_dot_account__pb2.ApiKeyRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountAdmins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.AccountService/CountAdmins',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.CountValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindByFeishuUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.AccountService/FindByFeishuUserId',
            priva__common_dot_dataplane_dot_v1_dot_account__pb2.FeishuRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_account__pb2.Account.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
