# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from priva_common.dataplane.v1 import admin_pb2 as priva__common_dot_dataplane_dot_v1_dot_admin__pb2
from priva_common.dataplane.v1 import common_pb2 as priva__common_dot_dataplane_dot_v1_dot_common__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in priva_common/dataplane/v1/admin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdminServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Healthz = channel.unary_unary(
                '/priva.dataplane.v1.AdminService/Healthz',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_admin__pb2.Health.FromString,
                _registered_method=True)
        self.Readyz = channel.unary_unary(
                '/priva.dataplane.v1.AdminService/Readyz',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_admin__pb2.Ready.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/priva.dataplane.v1.AdminService/Stats',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_admin__pb2.StatsResponse.FromString,
                _registered_method=True)


class AdminServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Healthz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Readyz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Healthz': grpc.unary_unary_rpc_method_handler(
                    servicer.Healthz,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_admin__pb2.Health.SerializeToString,
            ),
            'Readyz': grpc.unary_unary_rpc_method_handler(
                    servicer.Readyz,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_admin__pb2.Ready.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_admin__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'priva.dataplane.v1.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('priva.dataplane.v1.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Healthz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.AdminService/Healthz',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_admin__pb2.Health.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Readyz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.AdminService/Readyz',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_admin__pb2.Ready.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.AdminService/Stats',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_admin__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
