# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: priva_common/dataplane/v1/binding.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'priva_common/dataplane/v1/binding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from priva_common.dataplane.v1 import common_pb2 as priva__common_dot_dataplane_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'priva_common/dataplane/v1/binding.proto\x12\x12priva.dataplane.v1\x1a&priva_common/dataplane/v1/common.proto\"\x9d\x01\n\x07\x42inding\x12\x12\n\nbinding_id\x18\x01 \x01(\t\x12\x12\n\naccount_id\x18\x02 \x01(\t\x12\x14\n\x0csession_uuid\x18\x03 \x01(\t\x12\x16\n\x0e\x66irst_run_done\x18\x04 \x01(\x08\x12\x16\n\x0e\x66\x65ishu_chat_id\x18\x05 \x01(\t\x12\x10\n\x08\x62ound_at\x18\x06 \x01(\t\x12\x12\n\nrebound_at\x18\x07 \x01(\t\" \n\nBindingRef\x12\x12\n\nbinding_id\x18\x01 \x01(\t\"<\n\x0b\x42indingList\x12-\n\x08\x62indings\x18\x01 \x03(\x0b\x32\x1b.priva.dataplane.v1.Binding\"O\n\x0b\x42indRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x14\n\x0csession_uuid\x18\x02 \x01(\t\x12\x16\n\x0e\x66\x65ishu_chat_id\x18\x03 \x01(\t\"Q\n\rRebindRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x14\n\x0csession_uuid\x18\x02 \x01(\t\x12\x16\n\x0e\x66\x65ishu_chat_id\x18\x03 \x01(\t2\x8e\x03\n\x0e\x42indingService\x12\x44\n\x04\x42ind\x12\x1f.priva.dataplane.v1.BindRequest\x1a\x1b.priva.dataplane.v1.Binding\x12H\n\x06Rebind\x12!.priva.dataplane.v1.RebindRequest\x1a\x1b.priva.dataplane.v1.Binding\x12P\n\x0f\x43laimFirstRunIM\x12\x1e.priva.dataplane.v1.BindingRef\x1a\x1d.priva.dataplane.v1.BoolValue\x12I\n\nGetBinding\x12\x1e.priva.dataplane.v1.BindingRef\x1a\x1b.priva.dataplane.v1.Binding\x12O\n\x0cListBindings\x12\x1e.priva.dataplane.v1.AccountRef\x1a\x1f.priva.dataplane.v1.BindingListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'priva_common.dataplane.v1.binding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BINDING']._serialized_start=104
  _globals['_BINDING']._serialized_end=261
  _globals['_BINDINGREF']._serialized_start=263
  _globals['_BINDINGREF']._serialized_end=295
  _globals['_BINDINGLIST']._serialized_start=297
  _globals['_BINDINGLIST']._serialized_end=357
  _globals['_BINDREQUEST']._serialized_start=359
  _globals['_BINDREQUEST']._serialized_end=438
  _globals['_REBINDREQUEST']._serialized_start=440
  _globals['_REBINDREQUEST']._serialized_end=521
  _globals['_BINDINGSERVICE']._serialized_start=524
  _globals['_BINDINGSERVICE']._serialized_end=922
# @@protoc_insertion_point(module_scope)
