# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from priva_common.dataplane.v1 import binding_pb2 as priva__common_dot_dataplane_dot_v1_dot_binding__pb2
from priva_common.dataplane.v1 import common_pb2 as priva__common_dot_dataplane_dot_v1_dot_common__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in priva_common/dataplane/v1/binding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BindingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Bind = channel.unary_unary(
                '/priva.dataplane.v1.BindingService/Bind',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.BindRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.Binding.FromString,
                _registered_method=True)
        self.Rebind = channel.unary_unary(
                '/priva.dataplane.v1.BindingService/Rebind',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.RebindRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.Binding.FromString,
                _registered_method=True)
        self.ClaimFirstRunIM = channel.unary_unary(
                '/priva.dataplane.v1.BindingService/ClaimFirstRunIM',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.BindingRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.BoolValue.FromString,
                _registered_method=True)
        self.GetBinding = channel.unary_unary(
                '/priva.dataplane.v1.BindingService/GetBinding',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.BindingRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.Binding.FromString,
                _registered_method=True)
        self.ListBindings = channel.unary_unary(
                '/priva.dataplane.v1.BindingService/ListBindings',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.BindingList.FromString,
                _registered_method=True)


class BindingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Bind(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rebind(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimFirstRunIM(self, request, context):
        """atomic first_run_done 0→1
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBinding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBindings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BindingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Bind': grpc.unary_unary_rpc_method_handler(
                    servicer.Bind,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.BindRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.Binding.SerializeToString,
            ),
            'Rebind': grpc.unary_unary_rpc_method_handler(
                    servicer.Rebind,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.RebindRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.Binding.SerializeToString,
            ),
            'ClaimFirstRunIM': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimFirstRunIM,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.BindingRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.BoolValue.SerializeToString,
            ),
            'GetBinding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBinding,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.BindingRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.Binding.SerializeToString,
            ),
            'ListBindings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBindings,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_binding__pb2.BindingList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'priva.dataplane.v1.BindingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('priva.dataplane.v1.BindingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BindingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Bind(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.BindingService/Bind',
            priva__common_dot_dataplane_dot_v1_dot_binding__pb2.BindRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_binding__pb2.Binding.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rebind(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.BindingService/Rebind',
            priva__common_dot_dataplane_dot_v1_dot_binding__pb2.RebindRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_binding__pb2.Binding.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimFirstRunIM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.BindingService/ClaimFirstRunIM',
            priva__common_dot_dataplane_dot_v1_dot_binding__pb2.BindingRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBinding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.BindingService/GetBinding',
            priva__common_dot_dataplane_dot_v1_dot_binding__pb2.BindingRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_binding__pb2.Binding.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.BindingService/ListBindings',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_binding__pb2.BindingList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
