# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: priva_common/dataplane/v1/common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'priva_common/dataplane/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&priva_common/dataplane/v1/common.proto\x12\x12priva.dataplane.v1\"\x07\n\x05\x45mpty\"\x1a\n\tBoolValue\x12\r\n\x05value\x18\x01 \x01(\x08\"\x1b\n\nCountValue\x12\r\n\x05value\x18\x01 \x01(\x03\" \n\nAccountRef\x12\x12\n\naccount_id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'priva_common.dataplane.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=62
  _globals['_EMPTY']._serialized_end=69
  _globals['_BOOLVALUE']._serialized_start=71
  _globals['_BOOLVALUE']._serialized_end=97
  _globals['_COUNTVALUE']._serialized_start=99
  _globals['_COUNTVALUE']._serialized_end=126
  _globals['_ACCOUNTREF']._serialized_start=128
  _globals['_ACCOUNTREF']._serialized_end=160
# @@protoc_insertion_point(module_scope)
