# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from priva_common.dataplane.v1 import common_pb2 as priva__common_dot_dataplane_dot_v1_dot_common__pb2
from priva_common.dataplane.v1 import feishu_channel_config_pb2 as priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in priva_common/dataplane/v1/feishu_channel_config_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeishuChannelConfigServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/priva.dataplane.v1.FeishuChannelConfigService/Get',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.FromString,
                _registered_method=True)
        self.SetUser = channel.unary_unary(
                '/priva.dataplane.v1.FeishuChannelConfigService/SetUser',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.SetFeishuUserConfigRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.FromString,
                _registered_method=True)
        self.SetAdmin = channel.unary_unary(
                '/priva.dataplane.v1.FeishuChannelConfigService/SetAdmin',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.SetFeishuAdminConfigRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.FromString,
                _registered_method=True)
        self.SetStatus = channel.unary_unary(
                '/priva.dataplane.v1.FeishuChannelConfigService/SetStatus',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.SetFeishuStatusRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/priva.dataplane.v1.FeishuChannelConfigService/List',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfigList.FromString,
                _registered_method=True)
        self.ListEffective = channel.unary_unary(
                '/priva.dataplane.v1.FeishuChannelConfigService/ListEffective',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfigList.FromString,
                _registered_method=True)
        self.GetFeishuSecret = channel.unary_unary(
                '/priva.dataplane.v1.FeishuChannelConfigService/GetFeishuSecret',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuSecret.FromString,
                _registered_method=True)
        self.CreateLinkCode = channel.unary_unary(
                '/priva.dataplane.v1.FeishuChannelConfigService/CreateLinkCode',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.LinkCode.FromString,
                _registered_method=True)
        self.BindOwnerWithCode = channel.unary_unary(
                '/priva.dataplane.v1.FeishuChannelConfigService/BindOwnerWithCode',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.BindOwnerRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.BindOwnerResult.FromString,
                _registered_method=True)
        self.UnbindOwner = channel.unary_unary(
                '/priva.dataplane.v1.FeishuChannelConfigService/UnbindOwner',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.UnbindOwnerRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.FromString,
                _registered_method=True)
        self.GetPlatformConfig = channel.unary_unary(
                '/priva.dataplane.v1.FeishuChannelConfigService/GetPlatformConfig',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.ChannelPlatformConfig.FromString,
                _registered_method=True)
        self.SetPlatformConfig = channel.unary_unary(
                '/priva.dataplane.v1.FeishuChannelConfigService/SetPlatformConfig',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.SetChannelPlatformConfigRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.ChannelPlatformConfig.FromString,
                _registered_method=True)


class FeishuChannelConfigServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """empty account_id when unset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEffective(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFeishuSecret(self, request, context):
        """connector-only; plaintext
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateLinkCode(self, request, context):
        """USER route (control-panel)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BindOwnerWithCode(self, request, context):
        """CONNECTOR route
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnbindOwner(self, request, context):
        """USER route
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlatformConfig(self, request, context):
        """ADMIN route
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPlatformConfig(self, request, context):
        """ADMIN route
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeishuChannelConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.SerializeToString,
            ),
            'SetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.SetUser,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.SetFeishuUserConfigRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.SerializeToString,
            ),
            'SetAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAdmin,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.SetFeishuAdminConfigRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.SerializeToString,
            ),
            'SetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStatus,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.SetFeishuStatusRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfigList.SerializeToString,
            ),
            'ListEffective': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEffective,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfigList.SerializeToString,
            ),
            'GetFeishuSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFeishuSecret,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuSecret.SerializeToString,
            ),
            'CreateLinkCode': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateLinkCode,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.LinkCode.SerializeToString,
            ),
            'BindOwnerWithCode': grpc.unary_unary_rpc_method_handler(
                    servicer.BindOwnerWithCode,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.BindOwnerRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.BindOwnerResult.SerializeToString,
            ),
            'UnbindOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.UnbindOwner,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.UnbindOwnerRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.SerializeToString,
            ),
            'GetPlatformConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlatformConfig,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.ChannelPlatformConfig.SerializeToString,
            ),
            'SetPlatformConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPlatformConfig,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.SetChannelPlatformConfigRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.ChannelPlatformConfig.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'priva.dataplane.v1.FeishuChannelConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('priva.dataplane.v1.FeishuChannelConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeishuChannelConfigService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.FeishuChannelConfigService/Get',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.FeishuChannelConfigService/SetUser',
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.SetFeishuUserConfigRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.FeishuChannelConfigService/SetAdmin',
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.SetFeishuAdminConfigRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.FeishuChannelConfigService/SetStatus',
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.SetFeishuStatusRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.FeishuChannelConfigService/List',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfigList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEffective(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.FeishuChannelConfigService/ListEffective',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfigList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFeishuSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.FeishuChannelConfigService/GetFeishuSecret',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuSecret.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateLinkCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.FeishuChannelConfigService/CreateLinkCode',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.LinkCode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BindOwnerWithCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.FeishuChannelConfigService/BindOwnerWithCode',
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.BindOwnerRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.BindOwnerResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnbindOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.FeishuChannelConfigService/UnbindOwner',
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.UnbindOwnerRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.FeishuChannelConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlatformConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.FeishuChannelConfigService/GetPlatformConfig',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.ChannelPlatformConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPlatformConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.FeishuChannelConfigService/SetPlatformConfig',
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.SetChannelPlatformConfigRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_feishu__channel__config__pb2.ChannelPlatformConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
