# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from priva_common.dataplane.v1 import common_pb2 as priva__common_dot_dataplane_dot_v1_dot_common__pb2
from priva_common.dataplane.v1 import hook_policy_pb2 as priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in priva_common/dataplane/v1/hook_policy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HookPolicyServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/priva.dataplane.v1.HookPolicyService/List',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.ListHookPoliciesRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicyList.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/priva.dataplane.v1.HookPolicyService/Get',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicyRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicy.FromString,
                _registered_method=True)
        self.Upsert = channel.unary_unary(
                '/priva.dataplane.v1.HookPolicyService/Upsert',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.UpsertHookPolicyRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicy.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/priva.dataplane.v1.HookPolicyService/Delete',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicyRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
                _registered_method=True)


class HookPolicyServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """empty id => not found
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Upsert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """FAILED_PRECONDITION if predefined; NOT_FOUND if missing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HookPolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.ListHookPoliciesRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicyList.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicyRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicy.SerializeToString,
            ),
            'Upsert': grpc.unary_unary_rpc_method_handler(
                    servicer.Upsert,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.UpsertHookPolicyRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicy.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicyRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'priva.dataplane.v1.HookPolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('priva.dataplane.v1.HookPolicyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HookPolicyService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.HookPolicyService/List',
            priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.ListHookPoliciesRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicyList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.HookPolicyService/Get',
            priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicyRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Upsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.HookPolicyService/Upsert',
            priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.UpsertHookPolicyRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.HookPolicyService/Delete',
            priva__common_dot_dataplane_dot_v1_dot_hook__policy__pb2.HookPolicyRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
