# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: priva_common/dataplane/v1/network_isolation.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'priva_common/dataplane/v1/network_isolation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from priva_common.dataplane.v1 import common_pb2 as priva__common_dot_dataplane_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1priva_common/dataplane/v1/network_isolation.proto\x12\x12priva.dataplane.v1\x1a&priva_common/dataplane/v1/common.proto\"\xd4\x01\n\x10NetworkIsolation\x12\x1c\n\x14runner_deny_internal\x18\x01 \x01(\x08\x12\x1e\n\x16terminal_deny_internal\x18\x02 \x01(\x08\x12\x19\n\x11\x64\x65ny_tenant_peers\x18\x03 \x01(\x08\x12\x13\n\x0b\x65gress_mode\x18\x04 \x01(\t\x12>\n\x10\x65gress_allowlist\x18\x05 \x03(\x0b\x32$.priva.dataplane.v1.EgressAllowEntry\x12\x12\n\nupdated_at\x18\x06 \x01(\t\".\n\x10\x45gressAllowEntry\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"\xdf\x01\n\x1aSetNetworkIsolationRequest\x12\x1c\n\x14runner_deny_internal\x18\x01 \x01(\x08\x12\x1e\n\x16terminal_deny_internal\x18\x02 \x01(\x08\x12\x19\n\x11\x64\x65ny_tenant_peers\x18\x03 \x01(\x08\x12\x13\n\x0b\x65gress_mode\x18\x04 \x01(\t\x12>\n\x10\x65gress_allowlist\x18\x05 \x03(\x0b\x32$.priva.dataplane.v1.EgressAllowEntry\x12\x13\n\x0bupdate_mask\x18\x06 \x03(\t2\xbe\x01\n\x17NetworkIsolationService\x12\x46\n\x03Get\x12\x19.priva.dataplane.v1.Empty\x1a$.priva.dataplane.v1.NetworkIsolation\x12[\n\x03Set\x12..priva.dataplane.v1.SetNetworkIsolationRequest\x1a$.priva.dataplane.v1.NetworkIsolationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'priva_common.dataplane.v1.network_isolation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NETWORKISOLATION']._serialized_start=114
  _globals['_NETWORKISOLATION']._serialized_end=326
  _globals['_EGRESSALLOWENTRY']._serialized_start=328
  _globals['_EGRESSALLOWENTRY']._serialized_end=374
  _globals['_SETNETWORKISOLATIONREQUEST']._serialized_start=377
  _globals['_SETNETWORKISOLATIONREQUEST']._serialized_end=600
  _globals['_NETWORKISOLATIONSERVICE']._serialized_start=603
  _globals['_NETWORKISOLATIONSERVICE']._serialized_end=793
# @@protoc_insertion_point(module_scope)
