# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from priva_common.dataplane.v1 import common_pb2 as priva__common_dot_dataplane_dot_v1_dot_common__pb2
from priva_common.dataplane.v1 import quota_pb2 as priva__common_dot_dataplane_dot_v1_dot_quota__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in priva_common/dataplane/v1/quota_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QuotaServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/priva.dataplane.v1.QuotaService/Get',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_quota__pb2.Quota.FromString,
                _registered_method=True)
        self.Set = channel.unary_unary(
                '/priva.dataplane.v1.QuotaService/Set',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_quota__pb2.SetQuotaRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_quota__pb2.Quota.FromString,
                _registered_method=True)


class QuotaServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuotaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_quota__pb2.Quota.SerializeToString,
            ),
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_quota__pb2.SetQuotaRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_quota__pb2.Quota.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'priva.dataplane.v1.QuotaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('priva.dataplane.v1.QuotaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QuotaService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.QuotaService/Get',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_quota__pb2.Quota.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.QuotaService/Set',
            priva__common_dot_dataplane_dot_v1_dot_quota__pb2.SetQuotaRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_quota__pb2.Quota.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
