# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: priva_common/dataplane/v1/quota.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'priva_common/dataplane/v1/quota.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from priva_common.dataplane.v1 import common_pb2 as priva__common_dot_dataplane_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%priva_common/dataplane/v1/quota.proto\x12\x12priva.dataplane.v1\x1a&priva_common/dataplane/v1/common.proto\"z\n\x05Quota\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0c\n\x04tier\x18\x02 \x01(\t\x12\x1f\n\x17max_concurrent_sessions\x18\x03 \x01(\x05\x12\x1a\n\x12idle_grace_seconds\x18\x04 \x01(\x05\x12\x12\n\nupdated_at\x18\x05 \x01(\t\"\x85\x01\n\x0fSetQuotaRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0c\n\x04tier\x18\x02 \x01(\t\x12\x1f\n\x17max_concurrent_sessions\x18\x03 \x01(\x05\x12\x1a\n\x12idle_grace_seconds\x18\x04 \x01(\x05\x12\x13\n\x0bupdate_mask\x18\x05 \x03(\t2\x97\x01\n\x0cQuotaService\x12@\n\x03Get\x12\x1e.priva.dataplane.v1.AccountRef\x1a\x19.priva.dataplane.v1.Quota\x12\x45\n\x03Set\x12#.priva.dataplane.v1.SetQuotaRequest\x1a\x19.priva.dataplane.v1.Quotab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'priva_common.dataplane.v1.quota_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUOTA']._serialized_start=101
  _globals['_QUOTA']._serialized_end=223
  _globals['_SETQUOTAREQUEST']._serialized_start=226
  _globals['_SETQUOTAREQUEST']._serialized_end=359
  _globals['_QUOTASERVICE']._serialized_start=362
  _globals['_QUOTASERVICE']._serialized_end=513
# @@protoc_insertion_point(module_scope)
