# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: priva_common/dataplane/v1/registration.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'priva_common/dataplane/v1/registration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,priva_common/dataplane/v1/registration.proto\x12\x12priva.dataplane.v1\"\xfc\x01\n\x13PendingRegistration\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x13\n\x0brunner_type\x18\x04 \x01(\t\x12\x11\n\tcpu_cores\x18\x05 \x01(\x01\x12\x11\n\tmemory_mb\x18\x06 \x01(\x05\x12\x11\n\tvolume_gb\x18\x07 \x01(\x05\x12\x0c\n\x04note\x18\x08 \x01(\t\x12\x0e\n\x06status\x18\t \x01(\t\x12\x12\n\ncreated_at\x18\n \x01(\t\x12\x12\n\nupdated_at\x18\x0b \x01(\t\x12\x15\n\rpassword_hash\x18\x0c \x01(\t\"\xb1\x01\n\x14\x43reatePendingRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x15\n\rpassword_hash\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x13\n\x0brunner_type\x18\x04 \x01(\t\x12\x11\n\tcpu_cores\x18\x05 \x01(\x01\x12\x11\n\tmemory_mb\x18\x06 \x01(\x05\x12\x11\n\tvolume_gb\x18\x07 \x01(\x05\x12\x0c\n\x04note\x18\x08 \x01(\t\"\x1b\n\tStatusRef\x12\x0e\n\x06status\x18\x01 \x01(\t\" \n\nPendingRef\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"6\n\x10SetStatusRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"E\n\x0bPendingList\x12\x36\n\x05items\x18\x01 \x03(\x0b\x32\'.priva.dataplane.v1.PendingRegistration2\xe6\x02\n\x13RegistrationService\x12[\n\x06\x43reate\x12(.priva.dataplane.v1.CreatePendingRequest\x1a\'.priva.dataplane.v1.PendingRegistration\x12\x46\n\x04List\x12\x1d.priva.dataplane.v1.StatusRef\x1a\x1f.priva.dataplane.v1.PendingList\x12N\n\x03Get\x12\x1e.priva.dataplane.v1.PendingRef\x1a\'.priva.dataplane.v1.PendingRegistration\x12Z\n\tSetStatus\x12$.priva.dataplane.v1.SetStatusRequest\x1a\'.priva.dataplane.v1.PendingRegistrationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'priva_common.dataplane.v1.registration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PENDINGREGISTRATION']._serialized_start=69
  _globals['_PENDINGREGISTRATION']._serialized_end=321
  _globals['_CREATEPENDINGREQUEST']._serialized_start=324
  _globals['_CREATEPENDINGREQUEST']._serialized_end=501
  _globals['_STATUSREF']._serialized_start=503
  _globals['_STATUSREF']._serialized_end=530
  _globals['_PENDINGREF']._serialized_start=532
  _globals['_PENDINGREF']._serialized_end=564
  _globals['_SETSTATUSREQUEST']._serialized_start=566
  _globals['_SETSTATUSREQUEST']._serialized_end=620
  _globals['_PENDINGLIST']._serialized_start=622
  _globals['_PENDINGLIST']._serialized_end=691
  _globals['_REGISTRATIONSERVICE']._serialized_start=694
  _globals['_REGISTRATIONSERVICE']._serialized_end=1052
# @@protoc_insertion_point(module_scope)
