# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from priva_common.dataplane.v1 import registration_pb2 as priva__common_dot_dataplane_dot_v1_dot_registration__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in priva_common/dataplane/v1/registration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegistrationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/priva.dataplane.v1.RegistrationService/Create',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.CreatePendingRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingRegistration.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/priva.dataplane.v1.RegistrationService/List',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.StatusRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingList.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/priva.dataplane.v1.RegistrationService/Get',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingRegistration.FromString,
                _registered_method=True)
        self.SetStatus = channel.unary_unary(
                '/priva.dataplane.v1.RegistrationService/SetStatus',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.SetStatusRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingRegistration.FromString,
                _registered_method=True)


class RegistrationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """empty status => all
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.CreatePendingRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingRegistration.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.StatusRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingList.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingRegistration.SerializeToString,
            ),
            'SetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStatus,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.SetStatusRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingRegistration.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'priva.dataplane.v1.RegistrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('priva.dataplane.v1.RegistrationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegistrationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.RegistrationService/Create',
            priva__common_dot_dataplane_dot_v1_dot_registration__pb2.CreatePendingRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingRegistration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.RegistrationService/List',
            priva__common_dot_dataplane_dot_v1_dot_registration__pb2.StatusRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.RegistrationService/Get',
            priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingRegistration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.RegistrationService/SetStatus',
            priva__common_dot_dataplane_dot_v1_dot_registration__pb2.SetStatusRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_registration__pb2.PendingRegistration.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
