# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: priva_common/dataplane/v1/resource_spec.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'priva_common/dataplane/v1/resource_spec.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from priva_common.dataplane.v1 import common_pb2 as priva__common_dot_dataplane_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-priva_common/dataplane/v1/resource_spec.proto\x12\x12priva.dataplane.v1\x1a&priva_common/dataplane/v1/common.proto\"o\n\x0cResourceSpec\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x11\n\tcpu_cores\x18\x02 \x01(\x01\x12\x11\n\tmemory_mb\x18\x03 \x01(\x05\x12\x11\n\tvolume_gb\x18\x04 \x01(\x05\x12\x12\n\nupdated_at\x18\x05 \x01(\t\"z\n\x16SetResourceSpecRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x11\n\tcpu_cores\x18\x02 \x01(\x01\x12\x11\n\tmemory_mb\x18\x03 \x01(\x05\x12\x11\n\tvolume_gb\x18\x04 \x01(\x05\x12\x13\n\x0bupdate_mask\x18\x05 \x03(\t\"C\n\x10ResourceSpecList\x12/\n\x05specs\x18\x01 \x03(\x0b\x32 .priva.dataplane.v1.ResourceSpec2\xfc\x01\n\x13ResourceSpecService\x12G\n\x03Get\x12\x1e.priva.dataplane.v1.AccountRef\x1a .priva.dataplane.v1.ResourceSpec\x12S\n\x03Set\x12*.priva.dataplane.v1.SetResourceSpecRequest\x1a .priva.dataplane.v1.ResourceSpec\x12G\n\x04List\x12\x19.priva.dataplane.v1.Empty\x1a$.priva.dataplane.v1.ResourceSpecListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'priva_common.dataplane.v1.resource_spec_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESOURCESPEC']._serialized_start=109
  _globals['_RESOURCESPEC']._serialized_end=220
  _globals['_SETRESOURCESPECREQUEST']._serialized_start=222
  _globals['_SETRESOURCESPECREQUEST']._serialized_end=344
  _globals['_RESOURCESPECLIST']._serialized_start=346
  _globals['_RESOURCESPECLIST']._serialized_end=413
  _globals['_RESOURCESPECSERVICE']._serialized_start=416
  _globals['_RESOURCESPECSERVICE']._serialized_end=668
# @@protoc_insertion_point(module_scope)
