# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: priva_common/dataplane/v1/runner_defaults.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'priva_common/dataplane/v1/runner_defaults.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from priva_common.dataplane.v1 import common_pb2 as priva__common_dot_dataplane_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/priva_common/dataplane/v1/runner_defaults.proto\x12\x12priva.dataplane.v1\x1a&priva_common/dataplane/v1/common.proto\"\xb6\x01\n\x0eRunnerDefaults\x12\x1a\n\x12idle_grace_seconds\x18\x01 \x01(\x05\x12$\n\x1cmin_alive_after_wake_seconds\x18\x02 \x01(\x05\x12\x11\n\tcpu_cores\x18\x03 \x01(\x01\x12\x11\n\tmemory_mb\x18\x04 \x01(\x05\x12\x12\n\nstorage_gb\x18\x05 \x01(\x05\x12\x14\n\x0crunner_image\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t\"\xc1\x01\n\x18SetRunnerDefaultsRequest\x12\x1a\n\x12idle_grace_seconds\x18\x01 \x01(\x05\x12$\n\x1cmin_alive_after_wake_seconds\x18\x02 \x01(\x05\x12\x11\n\tcpu_cores\x18\x03 \x01(\x01\x12\x11\n\tmemory_mb\x18\x04 \x01(\x05\x12\x12\n\nstorage_gb\x18\x05 \x01(\x05\x12\x14\n\x0crunner_image\x18\x06 \x01(\t\x12\x13\n\x0bupdate_mask\x18\x07 \x03(\t2\xb6\x01\n\x15RunnerDefaultsService\x12\x44\n\x03Get\x12\x19.priva.dataplane.v1.Empty\x1a\".priva.dataplane.v1.RunnerDefaults\x12W\n\x03Set\x12,.priva.dataplane.v1.SetRunnerDefaultsRequest\x1a\".priva.dataplane.v1.RunnerDefaultsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'priva_common.dataplane.v1.runner_defaults_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNNERDEFAULTS']._serialized_start=112
  _globals['_RUNNERDEFAULTS']._serialized_end=294
  _globals['_SETRUNNERDEFAULTSREQUEST']._serialized_start=297
  _globals['_SETRUNNERDEFAULTSREQUEST']._serialized_end=490
  _globals['_RUNNERDEFAULTSSERVICE']._serialized_start=493
  _globals['_RUNNERDEFAULTSSERVICE']._serialized_end=675
# @@protoc_insertion_point(module_scope)
