# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from priva_common.dataplane.v1 import common_pb2 as priva__common_dot_dataplane_dot_v1_dot_common__pb2
from priva_common.dataplane.v1 import scheduler_pb2 as priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in priva_common/dataplane/v1/scheduler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateJob = channel.unary_unary(
                '/priva.dataplane.v1.SchedulerService/CreateJob',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Job.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/priva.dataplane.v1.SchedulerService/GetJob',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.JobRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Job.FromString,
                _registered_method=True)
        self.UpdateJob = channel.unary_unary(
                '/priva.dataplane.v1.SchedulerService/UpdateJob',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.UpdateJobRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Job.FromString,
                _registered_method=True)
        self.DeleteJob = channel.unary_unary(
                '/priva.dataplane.v1.SchedulerService/DeleteJob',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.JobRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/priva.dataplane.v1.SchedulerService/ListJobs',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.JobList.FromString,
                _registered_method=True)
        self.ListActiveJobs = channel.unary_unary(
                '/priva.dataplane.v1.SchedulerService/ListActiveJobs',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.JobList.FromString,
                _registered_method=True)
        self.SetJobStatus = channel.unary_unary(
                '/priva.dataplane.v1.SchedulerService/SetJobStatus',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.SetJobStatusRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Job.FromString,
                _registered_method=True)
        self.StartRun = channel.unary_unary(
                '/priva.dataplane.v1.SchedulerService/StartRun',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.StartRunRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Run.FromString,
                _registered_method=True)
        self.FinishRun = channel.unary_unary(
                '/priva.dataplane.v1.SchedulerService/FinishRun',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.FinishRunRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Run.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/priva.dataplane.v1.SchedulerService/ListRuns',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.RunPage.FromString,
                _registered_method=True)


class SchedulerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActiveJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinishRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.CreateJobRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Job.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.JobRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Job.SerializeToString,
            ),
            'UpdateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateJob,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.UpdateJobRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Job.SerializeToString,
            ),
            'DeleteJob': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteJob,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.JobRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.JobList.SerializeToString,
            ),
            'ListActiveJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActiveJobs,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.JobList.SerializeToString,
            ),
            'SetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJobStatus,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.SetJobStatusRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Job.SerializeToString,
            ),
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.StartRunRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Run.SerializeToString,
            ),
            'FinishRun': grpc.unary_unary_rpc_method_handler(
                    servicer.FinishRun,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.FinishRunRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Run.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.ListRunsRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.RunPage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'priva.dataplane.v1.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('priva.dataplane.v1.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.SchedulerService/CreateJob',
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.CreateJobRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Job.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.SchedulerService/GetJob',
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.JobRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Job.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.SchedulerService/UpdateJob',
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.UpdateJobRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Job.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.SchedulerService/DeleteJob',
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.JobRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.SchedulerService/ListJobs',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.AccountRef.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.JobList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActiveJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.SchedulerService/ListActiveJobs',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.JobList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.SchedulerService/SetJobStatus',
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.SetJobStatusRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Job.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.SchedulerService/StartRun',
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.StartRunRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinishRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.SchedulerService/FinishRun',
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.FinishRunRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.Run.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.SchedulerService/ListRuns',
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.ListRunsRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_scheduler__pb2.RunPage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
