# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: priva_common/dataplane/v1/secret.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'priva_common/dataplane/v1/secret.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from priva_common.dataplane.v1 import common_pb2 as priva__common_dot_dataplane_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&priva_common/dataplane/v1/secret.proto\x12\x12priva.dataplane.v1\x1a&priva_common/dataplane/v1/common.proto\"T\n\x06Secret\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06\x62undle\x18\x02 \x01(\t\x12\x12\n\ngeneration\x18\x03 \x01(\x03\x12\x12\n\nupdated_at\x18\x04 \x01(\t\"6\n\x10PutSecretRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x0e\n\x06\x62undle\x18\x02 \x01(\t\"&\n\x10GetSecretRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"(\n\x11SecretAccountList\x12\x13\n\x0b\x61\x63\x63ount_ids\x18\x01 \x03(\t2\xfe\x01\n\rSecretService\x12M\n\tPutSecret\x12$.priva.dataplane.v1.PutSecretRequest\x1a\x1a.priva.dataplane.v1.Secret\x12M\n\tGetSecret\x12$.priva.dataplane.v1.GetSecretRequest\x1a\x1a.priva.dataplane.v1.Secret\x12O\n\x0bListSecrets\x12\x19.priva.dataplane.v1.Empty\x1a%.priva.dataplane.v1.SecretAccountListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'priva_common.dataplane.v1.secret_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SECRET']._serialized_start=102
  _globals['_SECRET']._serialized_end=186
  _globals['_PUTSECRETREQUEST']._serialized_start=188
  _globals['_PUTSECRETREQUEST']._serialized_end=242
  _globals['_GETSECRETREQUEST']._serialized_start=244
  _globals['_GETSECRETREQUEST']._serialized_end=282
  _globals['_SECRETACCOUNTLIST']._serialized_start=284
  _globals['_SECRETACCOUNTLIST']._serialized_end=324
  _globals['_SECRETSERVICE']._serialized_start=327
  _globals['_SECRETSERVICE']._serialized_end=581
# @@protoc_insertion_point(module_scope)
