# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from priva_common.dataplane.v1 import common_pb2 as priva__common_dot_dataplane_dot_v1_dot_common__pb2
from priva_common.dataplane.v1 import secret_pb2 as priva__common_dot_dataplane_dot_v1_dot_secret__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in priva_common/dataplane/v1/secret_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SecretServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutSecret = channel.unary_unary(
                '/priva.dataplane.v1.SecretService/PutSecret',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_secret__pb2.PutSecretRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_secret__pb2.Secret.FromString,
                _registered_method=True)
        self.GetSecret = channel.unary_unary(
                '/priva.dataplane.v1.SecretService/GetSecret',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_secret__pb2.GetSecretRequest.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_secret__pb2.Secret.FromString,
                _registered_method=True)
        self.ListSecrets = channel.unary_unary(
                '/priva.dataplane.v1.SecretService/ListSecrets',
                request_serializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=priva__common_dot_dataplane_dot_v1_dot_secret__pb2.SecretAccountList.FromString,
                _registered_method=True)


class SecretServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PutSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSecret(self, request, context):
        """bundle decrypted; empty account_id when absent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSecrets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SecretServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.PutSecret,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_secret__pb2.PutSecretRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_secret__pb2.Secret.SerializeToString,
            ),
            'GetSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSecret,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_secret__pb2.GetSecretRequest.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_secret__pb2.Secret.SerializeToString,
            ),
            'ListSecrets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSecrets,
                    request_deserializer=priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=priva__common_dot_dataplane_dot_v1_dot_secret__pb2.SecretAccountList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'priva.dataplane.v1.SecretService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('priva.dataplane.v1.SecretService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SecretService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PutSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.SecretService/PutSecret',
            priva__common_dot_dataplane_dot_v1_dot_secret__pb2.PutSecretRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_secret__pb2.Secret.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.SecretService/GetSecret',
            priva__common_dot_dataplane_dot_v1_dot_secret__pb2.GetSecretRequest.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_secret__pb2.Secret.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSecrets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/priva.dataplane.v1.SecretService/ListSecrets',
            priva__common_dot_dataplane_dot_v1_dot_common__pb2.Empty.SerializeToString,
            priva__common_dot_dataplane_dot_v1_dot_secret__pb2.SecretAccountList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
