import {
  Activity,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Brain,
  Bug,
  Camera,
  ChartBar,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  Clipboard,
  Cloud,
  Code,
  Copy,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Eye,
  File,
  FileCode,
  FileMinus,
  FilePlus,
  Files,
  FileText,
  Flag,
  Folder,
  Gauge,
  GitBranch,
  GitMerge,
  GitPullRequest,
  Globe,
  Hammer,
  Heart,
  Image,
  Info,
  Key,
  Layers,
  Link,
  List,
  ListChecks,
  Lock,
  Mail,
  MessageSquare,
  Mic,
  Minus,
  Music,
  Package,
  Pause,
  PenTool,
  Play,
  Plus,
  Puzzle,
  RefreshCw,
  Rocket,
  RotateCw,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  Sparkles,
  Square,
  Star,
  Tag,
  Terminal,
  Trash2,
  TrendingUp,
  Unlock,
  Upload,
  User,
  UserPlus,
  Users,
  Video,
  Wrench,
  X,
  Zap,
} from 'lucide-react'

export const ICON_NAMES = [
  'zap', 'file-text', 'code', 'terminal', 'search', 'message-square', 'send',
  'book-open', 'pen-tool', 'git-branch', 'git-merge', 'git-pull-request',
  'bug', 'shield', 'lock', 'unlock', 'key', 'settings', 'wrench', 'hammer',
  'rocket', 'sparkles', 'star', 'heart', 'bookmark', 'flag', 'tag',
  'folder', 'file', 'file-code', 'file-plus', 'file-minus', 'files',
  'database', 'server', 'cloud', 'globe', 'link', 'external-link',
  'eye', 'list', 'list-checks', 'check-circle', 'alert-triangle', 'info',
  'play', 'pause', 'square', 'refresh-cw', 'rotate-cw', 'download', 'upload',
  'clipboard', 'copy', 'scissors', 'trash-2', 'archive',
  'cpu', 'bot', 'brain', 'puzzle', 'layers', 'box', 'package',
  'chart-bar', 'trending-up', 'activity', 'gauge',
  'users', 'user', 'user-plus', 'mail', 'bell',
  'image', 'camera', 'video', 'music', 'mic',
  'arrow-right', 'arrow-left', 'arrow-up', 'arrow-down',
  'chevron-right', 'chevron-down', 'plus', 'minus', 'x',
]

export const ICON_MAP = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  archive: Archive,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  bell: Bell,
  'book-open': BookOpen,
  bookmark: Bookmark,
  bot: Bot,
  box: Box,
  brain: Brain,
  bug: Bug,
  camera: Camera,
  'chart-bar': ChartBar,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  clipboard: Clipboard,
  cloud: Cloud,
  code: Code,
  copy: Copy,
  cpu: Cpu,
  database: Database,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  file: File,
  'file-code': FileCode,
  'file-minus': FileMinus,
  'file-plus': FilePlus,
  files: Files,
  'file-text': FileText,
  flag: Flag,
  folder: Folder,
  gauge: Gauge,
  'git-branch': GitBranch,
  'git-merge': GitMerge,
  'git-pull-request': GitPullRequest,
  globe: Globe,
  hammer: Hammer,
  heart: Heart,
  image: Image,
  info: Info,
  key: Key,
  layers: Layers,
  link: Link,
  list: List,
  'list-checks': ListChecks,
  lock: Lock,
  mail: Mail,
  'message-square': MessageSquare,
  mic: Mic,
  minus: Minus,
  music: Music,
  package: Package,
  pause: Pause,
  'pen-tool': PenTool,
  play: Play,
  plus: Plus,
  puzzle: Puzzle,
  'refresh-cw': RefreshCw,
  rocket: Rocket,
  'rotate-cw': RotateCw,
  scissors: Scissors,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  shield: Shield,
  sparkles: Sparkles,
  square: Square,
  star: Star,
  tag: Tag,
  terminal: Terminal,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  unlock: Unlock,
  upload: Upload,
  user: User,
  'user-plus': UserPlus,
  users: Users,
  video: Video,
  wrench: Wrench,
  x: X,
  zap: Zap,
}

export function getLucideIcon(iconName, fallback = Zap) {
  return ICON_MAP[iconName] || fallback
}
